### PR TITLE
Improve default security to from 58-bits to 72-bits

### PR DESCRIPTION
**Pull request by atoponce**
Best practice for offline password cracking security to have an entropy of at least 70-bits in the system when generating passwords. Consider the following clustered computing projects to prove this:

Bitcoin mining is currently calculating SHA-256 hashes at a pace of:

    * 8,072,925.27 TH/s or 8.073x10^18 hashes per second [0]
    * 62-bits per second
    * 74-bits per hour
    * 79-bits per day
    * 87-bits per year

distributed.net is searching for a 72-bit RC5 key at a sustained pace of:

    * 799,912,853,455 kps or 800 billion keys per second [1]
    * 39-bits per second
    * 51-bits per hour
    * 55-bits per day
    * 64-bits per year

A recent clustered password cracking project cracked 320 million SHA-1 password
hashes at a peak rate of:

    * 180 GHps or 180 billion hashes per second [2]
    * 37-bits per second
    * 49-bits per hour
    * 53-bits per day
    * 62-bits per year

0. https://blockchain.info/charts/hash-rate
1. https://stats.distributed.net/projects.php?project_id=8
2. https://cynosureprime.blogspot.com/2017/08/320-million-hashes-exposed.html

While I think it's fair to say that the password hashing speeds of Bitcoin are unrealistic for practical password cracking situations, the distributed.net and MDXfind/Hashcat scenarios with 25 GPUs are not.

As a result, it should be considered "best practice" to move password entropy into the 70-bit security margin to prevent professional password crackers from realistically exhausting 1/2 of the password space.

### CODE REVIEW

**Comment by maxtaco** [comment]
Agreed, thanks!  I should also switch 1SP over to a memory-hard stretcher that hasn't been so threatened by what's happening in bitcoin mining.

**Comment by atoponce** [comment]
Thanks for merging!

I noticed you may be considering scrypt. I personally would recommend Argon2id. It's the Password Hashing Competition winner, and has more sane controls over CPU and memory hardness than scrypt. With that said, what is presented to the user should be sane defaults, rather than letting them have full control over those hardness costs.

Anyway, I'm really impressed with this project. Thanks for putting it together.

**Comment by maxtaco** [comment]
Thanks @atoponce. Yeah, I've been hearing good things about Argon2. Right now 1SP is just a hobby, so I don't have much time to improve it.

**Comment by atoponce** [comment]
No worries. [I compiled a list](https://docs.google.com/spreadsheets/d/1ucaqJ4U3X3nNEbAAa06igbBkITHaA98blftOwT8u0I4/edit?usp=sharing) of passphrase and password generators online, and I'm submitting pull requests where possible to help improve their security. When this merge lands on the main site, I'll update the spreadsheet. :)

**Comment by maxtaco** [comment]
ok, thanks for the feedback, this is live

**Pull request merged**
